makefile: force $ENV vars to be passed (Ypnose)..
Ypnose reported in [1] that compilation failed when being done in
the Void Linux package build system.

  [1] http://article.gmane.org/gmane.mail.s-nail.user/219

He posted the config.log:

  **********
  *** checking if a hello world program can be built ...
  *** test program is
  #include <stdio.h>

  int main(int argc, char *argv[])
  {
     (void)argc;
     (void)argv;
     puts("hello world");
     return 0;
  }
  *** results are
  make[1]: Entering directory '/builddir/s-nail-14.7.10'
  /usr/lib/ccache/bin/clang  -o ___tmp1162 ___tmp1162.c
  ccache: error: Could not find compiler "clang" in PATH
  config.mk:7: recipe for target '___tmp1162' failed
  make[1]: *** [___tmp1162] Error 1
  make[1]: Leaving directory '/builddir/s-nail-14.7.10'
  *** no

Since the propsed fix was

  - make PREFIX=/usr ...
  + make CC=$CC PREFIX=/usr ...

i finally assume that environment variables that are defined by
make(1) itself by definition are not passed through to
subprocesses by the used make(1) but instead reset to the make(1)
default-ones.  I have seen similar problems for S-CText, fixed
there for example on 2014-04-14 in [7cc84aa] by explicitly setting
the variable (as shown above) when calling those.

Let's see if that fixes Void Linux.  If not i think we either have
to document this problem (as for UnixWare where you have to pass
-e, but which has unfortunate side-effects) or even replace the
entire build system by renaming mk-conf.sh to configure and using
a "./configure && make && make install" cycle.  Yuck!